### ISSUE TITLE
msg.sig and msg.pubkey

### ISSUE THREAD

**Issue by staltz** [ahdinosaur/ppppp-rs#3]
https://github.com/ahdinosaur/ppppp-rs/blob/34913047b11703bb2c90e5c1e48355979a682468/ppppp-msg/src/msg.rs#L18

It should be `sig` instead of signature, and msg.pubkey is missing.

**Comment by ahdinosaur** [comment]
thanks for the code review! :purple_heart: 

> It should be sig instead of signature,

i'm using a [serde field attribute `rename`](https://serde.rs/field-attrs.html#rename) to rename `sig` -> `signature` (and back) on serialize / deserialize.

see the line above:

https://github.com/ahdinosaur/ppppp-rs/blob/3491304/ppppp-msg/src/msg.rs#L17C1-L17C1

> msg.pubkey is missing.

yes, this code is still leftover from my MsgV1 port 6 months ago, haven't finished the MsgV3 upgrade.

last night i realized i missed that and now is added:

https://github.com/ahdinosaur/ppppp-rs/blob/6b623a7/ppppp-msg/src/msg.rs#L28-L29
