### ISSUE TITLE
msg.data_type

### ISSUE THREAD

**Issue by staltz** [ahdinosaur/ppppp-rs#4]
https://github.com/ahdinosaur/ppppp-rs/blob/34913047b11703bb2c90e5c1e48355979a682468/ppppp-msg/src/msg.rs#L39

What's this? :)

**Comment by ahdinosaur** [comment]
was previously `type` (with [serde renamed](https://serde.rs/field-attrs.html#rename) to `data_type`), last night i realized was accidentally leftover and replaced by `domain`.

so here's where i got up to last night: https://github.com/ahdinosaur/ppppp-rs/blob/6b623a7/ppppp-msg/src/msg.rs#L91-L106
